apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: behandler-kontroll
  namespace: default
  labels:
    team: "dsopkontroll"
spec:
  name: "pale-2"
  image: "repo.adeo.no:5443/dsop-kontroll/behandler-kontroll:@@VERSION@@"
  replicas:
    min: 1
    max: 6
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
  env:
  - name: APPLICATION_THREADS
    value: '{{APPLICATION_THREADS}}'
